import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const geist = Geist({
	subsets: ["latin"],
	display: "swap",
});

const geistMono = Geist_Mono({
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(geist.className, geistMono.className)}
			suppressHydrationWarning /* Required for next-themes */
		>
			{/* React Scan */}
			{process.env.NODE_ENV === "development" && (
				<head>
					<script src="https://unpkg.com/react-scan/dist/auto.global.js" />
				</head>
			)}
			<body>
				<div className="antialiased font-sans bg-background text-foreground min-h-screen w-screen">
					<Providers>{children}</Providers>
				</div>
			</body>
		</html>
	);
}
